export const ROUTES = {
  HOME: "/",
  SETTINGS: "/settings",
  LOGIN: "/login",
  REGISTER: "/register",
  SIGNUP: "/signup",
  ABOUT: "/about",
  CONTACT: "/contact",
  VIEW_DOCUMENTATION: "/view-documentation",
  CREATE_DOCUMENTATION: "/create-documentation",
  LIST_PROJECTS: "/list-projects",
  CREATE_PROJECT: "/create-project",
  VIEW_PROJECT: "/project",
  PROFILE: "/profile",
};
